### ISSUE TITLE
 'pcl_mesh_sampling' No such file or directory: 

### ISSUE THREAD

**Issue by albertotono** [PointCloudLibrary/pcl#4530]
```
Traceback (most recent call last):
  File "utils/ply_to_pcd.py", line 45, in <module>
    ply_to_pcd(categories)
  File "utils/ply_to_pcd.py", line 40, in ply_to_pcd
    call(['pcl_mesh_sampling', file, file.replace('ply', 'pcd'),
  File "/home/alberto/anaconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/alberto/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/alberto/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pcl_mesh_sampling'
```

**Comment by albertotono** [comment]
`sudo apt --fix-broken install `
and then 
`sudo apt-get install pcl-tools`
fixed it
