### ISSUE TITLE
[polygonmesh] viewer->addPolygonMesh fails on Linux Alpine 3.15

### ISSUE THREAD

**Issue by danielTobon43** [PointCloudLibrary/pcl#5362]
**Describe the bug**

Displaying a polygon mesh on` pcl::visualization::PCLVisualizer::Ptr viewer` fails in Linux Alpine.

**Context**

I have a C++ project running with PCL 1.12.1 on Linux alpine 3.15 where a pointcloud is converted into a mesh using `poisson/gp3`. The conversion is working fine since I have exported the mesh with:

`pcl::io::savePLYFileBinary(output_dir.c_str(),cloud_mesh);`

and visualized it on [3dviewer.net](https://3dviewer.net/) and looks fine:

![Screenshot from 2022-07-29 08-46-51](https://user-images.githubusercontent.com/35694200/181774555-6e8c4c43-e043-415d-86e2-9d247f6fceba.png)

My output from PCL visualizer without adding 

`viewer->addPolygonMesh(mesh,"mesh",PORT2);`

is as follows:

![Screenshot from 2022-07-29 08-49-18](https://user-images.githubusercontent.com/35694200/181774771-a2155a5b-b390-426c-b31c-db3bac67310c.png)

After I set `viewer->addPolygonMesh(mesh,"mesh",PORT2);` the visualizer crash and then:

`Segmentation fault (core dumped)`

**Note:**
PCL 1.12.1 runs with no issue on Linux Alpine. The problem seems to be related to the visualizer adding the mesh object for displaying it.

Log from debugging with `gdb`

```
saved mesh in:./cloud_mesh.ply
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open i915: Error loading shared library /usr/lib/xorg/modules/dri/i915_dri.so: No such file or directory (search paths /usr/lib/xorg/modules/dri, suffix _dri)
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: crocus
[New LWP 81]
[New LWP 82]
[New LWP 83]
[New LWP 84]
[New LWP 85]
Thread 1 "pointcloudToMES" received signal SIGSEGV, Segmentation fault.
0x00007f529f8a2882 in ?? () from /lib/ld-musl-x86_64.so.1
```

**backtrace**

```
(gdb) bt
#0  0x00007f529f8a2882 in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x00007f529f8a2c2e in ?? () from /lib/ld-musl-x86_64.so.1
#2  0x00007f529f8b55a0 in munmap () from /lib/ld-musl-x86_64.so.1
#3  0x00007fffb80e9000 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x00007fffb80e90b0 in ?? ()
#6  0x00005599cbb106a7 in std::_Sp_counted_ptr<pcl::PointCloud<pcl::PointXYZ>*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (
    this=0x3ca6000000000c) at /usr/include/c++/10.3.1/bits/shared_ptr_base.h:380
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Log from debugging with `strace`

```
mremap(0x7f63ac0e8000, 266240, 528384, MREMAP_MAYMOVE) = 0x7f63ac067000
mremap(0x7f63ac129000, 135168, 266240, MREMAP_MAYMOVE) = 0x7f63ac0e8000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f63ac167000
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f63ac15f000
munmap(0x7f63ac187000, 163840)          = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

This project has been tested on Ubuntu 20.04 and is working well, so my guess is there is some kind of issue with Linux Alpine.

**Expected behavior**

Display a mesh polygon file in the PCL visualizer using Linux Alpine (this works with standard point clouds)

**Current Behavior**

Segmentation fault (core dumped)

**To Reproduce**
- `git clone https://github.com/danielTobon43/pointcloudToMesh`
- `mkdir build && cd build && cmake ../ && make`

```
./pointcloudToMESH <input cloud> <surface method estimation> <normal method estimation> <output dir>

surface method estimation:
    1 --> for poisson
    2 --> for gp3
    
normal method estimation.
    1 --> for normal estimation
    2 --> for mls normal estimation
    
 example:
 ./pointcloudToMESH /home/xXx/PCD-PLY_Files/cloud.txt 2 1 /home/xXx/Desktop    
```

**Environment**
 - OS: Linux Alpine 3.15
 - Compiler: gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027
 - PCL Version: 1.12.1 archive release package

**Possible Solution**

- I have installed `mesa-dri-classic` to provide `i915` driver, but the problem still persists.
- I have recompiled PCL with `-DPCL_ENABLE_AVX=OFF`
- I have set these flags in the project

```
add_compile_options(--param l1-cache-size=32)
add_compile_options(--param l1-cache-line-size=64)
add_compile_options(--param l2-cache-size=3072)
```

and

```
target_compile_options(${PROJECT_NAME} PRIVATE -Wno-cpp
    -mmmx
    -msse
    -msse2
    -msse3
    -mssse3
    -msse4.2
    -msse4.1
    -mno-sse4a
    -mno-avx
    -mno-avx2
    -mno-fma
    -mno-fma4
    -mno-f16c
    -mno-xop
    -mno-bmi
    -mno-bmi2
    -mrdrnd
    -mno-3dnow
    -mlzcnt
    -mfsgsbase
    -mpclmul
    -mtune=haswell
    -march=haswell
)
```

**Additional context**

I have found this post where the problem might be related to the alignment but I am still not sure how to fix it.

- https://reverseengineering.stackexchange.com/questions/21503/unexpected-segfault-when-theres-apparently-nothing-that-would-cause-it

**Comment by danielTobon43** [comment]
I will compile the master branch version of PCL to see if the problem might be related to the `Segmentation fault (core dumped)` in the visualizer since I saw a post that this issue was fixed in the master branch.

**Comment by mvieth** [comment]
Could you perhaps also run valgrind? That might give us some additional useful information.
When you compile PCL's master branch, can you choose to add debug symbols (e.g. RelWithDebInfo CMake config)? The backtrack is missing some information, all I can see is that the segfault is related to a shared pointer.

**Comment by mvieth** [comment]
Note: PCL is AFAIK not regularly tested with musl. Do you know whether PCL's tests are run on Linux Alpine somewhere?

**Comment by danielTobon43** [comment]
> Could you perhaps also run valgrind? That might give us some additional useful information. When you compile PCL's master branch, can you choose to add debug symbols (e.g. RelWithDebInfo CMake config)? The backtrack is missing some information, all I can see is that the segfault is related to a shared pointer.

That was the information from bt command, do you know a flag for -verbose or something like that?

**Comment by danielTobon43** [comment]
> Note: PCL is AFAIK not regularly tested with musl. Do you know whether PCL's tests are run on Linux Alpine somewhere?

Well, there is a `pcl-dev `package for Linux Alpine [here](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/pcl-dev) and, what i can tell there was no issue during compiling and testing, although some tests were disabled

build log: https://build.alpinelinux.org/buildlogs/build-edge-x86_64/testing/pcl/pcl-1.12.1-r2.log

**Comment by mvieth** [comment]
> That was the information from bt command, do you know a flag for -verbose or something like that?

What I meant was: When the bt command shows `??` that can mean that debug info is not included in the library/binaries. According to the build log you posted, the PCL package is build in the "Release" CMake configuration (`CMAKE_BUILD_TYPE`), meaning that no debug info is contained. Other configurations like "RelWithDebInfo" put this debug info into the libraries/binaries. Then debuggers can show more informative output.

> Well, there is a `pcl-dev `package for Linux Alpine [here](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/pcl-dev) and, what i can tell there was no issue during compiling and testing, although some tests were disabled
> 
> build log: https://build.alpinelinux.org/buildlogs/build-edge-x86_64/testing/pcl/pcl-1.12.1-r2.log

From what I can see in the log, the tests are built but not actually run. One line says `No tests were found!!!`

**Comment by mvieth** [comment]
So the shared pointer that causes the problem seems to be this one:
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/pcl_visualizer.cpp#L3106
And the error happens when the pointer is destroyed/the contained cloud deleted:
https://github.com/gcc-mirror/gcc/blob/releases/gcc-10.3.0/libstdc++-v3/include/bits/shared_ptr_base.h#L380
But I still have no idea why it happens. Output from valgrind or a more informative backtrace could tell us more.
I found this loosely related problem, maybe that can help you: https://github.com/lovell/sharp/issues/2570

**Comment by danielTobon43** [comment]
Hi @mvieth I have compiled the release package version of PCL with `RelWithDebInfo` and again with `Release`, which is working for some strange reason for both versions. Since I am refactoring the original code from the project, I think I have a bug on my part.

![Screenshot from 2022-08-01 09-24-28](https://user-images.githubusercontent.com/35694200/182169685-1b95ec84-2582-4b3b-8827-7495c8a433d5.png)

I will keep doing some tests to make sure and if I got the same error I will re-open the issue. Thanks for your help.

**Comment by danielTobon43** [comment]
So, Indeed there is an error. When I linked an external library to the project that has nothing to do with the main function it crash the program. It is strange because I am not using the external library, just linking it into the main program and everything runs fine until the polygon mesh is added to the visualizer, then the program crashes.

Log from `gdb` using the `RelWithDebInfo` version

```
(gdb) r
Starting program: /tmp/build/pointcloudToMESH Tree2.pcd 2 1 .
warning: Error disabling address space randomization: Operation not permitted

> Loading 
Found pcd file.
[done, 1.94198e+07 ms : 832335 points]
[New LWP 272]
Using normal method estimation...[OK]
Applying surface meshing...Using surface method: gp3 ...
Not enough neighbors are considered: source of R=150 is out of range! Consider increasing nnn_...
Not enough neighbors are considered: ffn or sfn out of range! Consider increasing nnn_... Setting R=74781 to be BOUNDARY!
Number of neighborhood size increase requests for fringe neighbors: 2797
Number of neighborhood size increase requests for source: 4036
[OK]
saved mesh in:./cloud_mesh.ply
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open i915: Error loading shared library /usr/lib/xorg/modules/dri/i915_dri.so: No such file or directory (search paths /usr/lib/xorg/modules/dri, suffix _dri)
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: crocus
[New LWP 273]
[New LWP 274]
[New LWP 275]
[New LWP 276]
[New LWP 277]

Thread 1 "pointcloudToMES" received signal SIGSEGV, Segmentation fault.
0x00007f263a43c88d in ?? () from /lib/ld-musl-x86_64.so.1
(gdb) 
(gdb) bt
#0  0x00007f263a43c88d in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x00007f263a43cc2e in ?? () from /lib/ld-musl-x86_64.so.1
#2  0x00007f263a44f5a0 in munmap () from /lib/ld-musl-x86_64.so.1
#3  0x00007f261d5b889c in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x00007ffc5fe1ad88 in ?? ()
#6  0x00007f2636e5d544 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x7f262c8ae370) at /usr/include/c++/10.3.1/bits/shared_ptr_base.h:158
#7  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (
    this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.3.1/bits/shared_ptr_base.h:736
#8  std::__shared_ptr<pcl::PointCloud<pcl::PointXYZ>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.3.1/bits/shared_ptr_base.h:1188
#9  std::shared_ptr<pcl::PointCloud<pcl::PointXYZ> >::~shared_ptr (
    this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.3.1/bits/shared_ptr.h:121
#10 pcl::visualization::PCLVisualizer::addPolygonMesh (this=0x7f2632dde0d0, 
    poly_mesh=..., id=..., viewport=2)
    at /tmp/pcl-pcl-1.12.1/visualization/src/pcl_visualizer.cpp:3092
#11 0x000055fa08e00e55 in vizualizeMesh(std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&, pcl::PolygonMesh&) ()
#12 0x000055fa08dfe836 in main ()

```

Log from `valgrind`

```
==278==    by 0x11A6A7EA: ??? (in /usr/lib/xorg/modules/dri/swrast_dri.so)
==278==    by 0x11A7007B: ??? (in /usr/lib/xorg/modules/dri/swrast_dri.so)
==278==    by 0x11A6F9BD: ??? (in /usr/lib/xorg/modules/dri/swrast_dri.so)
==278==    by 0x4053220: ??? (in /lib/ld-musl-x86_64.so.1)
==278== 
^C==278== 
==278== Process terminating with default action of signal 2 (SIGINT)
==278==    at 0x4055413: ??? (in /lib/ld-musl-x86_64.so.1)
==278==    by 0x405272C: ??? (in /lib/ld-musl-x86_64.so.1)
==278==    by 0xDEFCE3B: ??? (in /usr/lib/libvtkjsoncpp.so.9.1.0)
==278== 
==278== HEAP SUMMARY:
==278==     in use at exit: 356,172,600 bytes in 1,484,798 blocks
==278==   total heap usage: 18,999,401 allocs, 17,514,604 frees, 42,354,832,263 bytes allocated
==278== 
==278== LEAK SUMMARY:
==278==    definitely lost: 151 bytes in 2 blocks
==278==    indirectly lost: 0 bytes in 0 blocks
==278==      possibly lost: 78,363,405 bytes in 6,812 blocks
==278==    still reachable: 277,809,044 bytes in 1,477,984 blocks
==278==         suppressed: 0 bytes in 0 blocks
==278== Rerun with --leak-check=full to see details of leaked memory
==278== 
==278== Use --track-origins=yes to see where uninitialised values come from
==278== For lists of detected and suppressed errors, rerun with: -s
==278== ERROR SUMMARY: 7337 errors from 304 contexts (suppressed: 0 from 0)

```

Running the program with valgrind displayed the mesh fine. This is just to weird

**Comment by danielTobon43** [comment]
After I removed the external library from target_link... then it works as expected

```
/tmp/build # gdb --args ./pointcloudToMESH Tree2.pcd 2 1 .
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./pointcloudToMESH...
(gdb) r
Starting program: /tmp/build/pointcloudToMESH Tree2.pcd 2 1 .
warning: Error disabling address space randomization: Operation not permitted
> Loading 
Found pcd file.
[done, 2.45811e+07 ms : 832335 points]
[New LWP 865]
Using normal method estimation...[OK]
Applying surface meshing...Using surface method: gp3 ...
Not enough neighbors are considered: source of R=150 is out of range! Consider increasing nnn_...
Not enough neighbors are considered: ffn or sfn out of range! Consider increasing nnn_... Setting R=74781 to be BOUNDARY!
Number of neighborhood size increase requests for fringe neighbors: 2797
Number of neighborhood size increase requests for source: 4036
[OK]
saved mesh in:./cloud_mesh.ply
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open i915: Error loading shared library /usr/lib/xorg/modules/dri/i915_dri.so: No such file or directory (search paths /usr/lib/xorg/modules/dri, suffix _dri)
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: crocus
[New LWP 866]
[New LWP 867]
[New LWP 868]
[New LWP 869]
[New LWP 870]
Press [q] to exit!
```
I think I will stick to the ubuntu version for my project seems there is something weird with Linux Alpine.

**Comment by mvieth** [comment]
Strange indeed. Out of interest, which external library are you linking with?
Actually, I see no reason why the cloud in `addPolygonMesh` (https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/pcl_visualizer.cpp#L3106) has to be a shared pointer. It could just as well be an object on the stack. I guess that should fix this problem, but of course that's no guarantee that a similar problem won't show up elsewhere ...

**Comment by danielTobon43** [comment]
> Strange indeed. Out of interest, which external library are you linking with? Actually, I see no reason why the cloud in `addPolygonMesh` (https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/pcl_visualizer.cpp#L3106) has to be a shared pointer. It could just as well be an object on the stack. I guess that should fix this problem, but of course that's no guarantee that a similar problem won't show up elsewhere ...

I was linking [argparse](https://github.com/p-ranav/argparse), but never used the `#include` statement in the main project. Also, this library is a header only.
