### ISSUE TITLE
some problem about pcl and eigen

### ISSUE THREAD

**Issue by timetosaygoodb** [PointCloudLibrary/pcl#5831]
My code,Test3Dto3Dmatch.cpp, runs successfully when compiled in Debug mode. However, when I compile it in Release mode, I encounter a heap-buffer-overflow issue. To debug this, I added "-fno-omit-frame-pointer" and "-fsanitize=address" to the CMakeLists file. The error seems to occur within the Eigen library at Eigen::internal::handmade_aligned_free(void)*. I suspect the issue may be within functions like bimToslam::ISSextractor::operator() and bimToslam::Frontend::ExtractandMatchISS(), which are used for point cloud feature extraction. To investigate further, I created a new test file, TestISSextractor.cpp, and removed the parts related to Eigen. However, I still encounter the same error, roughly as follows:

==21835==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fffd3e607f8 at pc 0x5555555e6f82 bp 0x7fffda9fd3e0 sp 0x7fffda9fd3d0 READ of size 8 at 0x7fffd3e607f8 thread T1 ... 0x7fffd3e607f8 is located 8 bytes to the left of 15672944-byte region [0x7fffd3e60800,0x7fffd4d52e70) allocated by thread T1 here: #0 0x7ffff6ef6b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40) https://github.com/timetosaygoodb/bimToslam/issues/1 0x7ffff602fa88 in Eigen::internal::aligned_malloc(unsigned long) (/usr/lib/x86_64-linux-gnu/libpcl_filters.so.1.8+0x311a88)

I tried searching online and found similar issues, suggesting a problem between PCL and Eigen libraries. Some solutions involve enabling AVX instruction sets, so I added "-mavx2" in the CMakeLists file, but the issue remains unresolved. [https://github.com/timetosaygoodb/bimToslam](url)Here is my code

**Comment by mvieth** [comment]
Try also `-march=native` or `-msse4.2`.
However, your PCL version is quite old, and I would recommend you to switch to a newer one. I believe there was a fix since then that solved this problem (on Linux, when using CMake).

**Comment by timetosaygoodb** [comment]
> Try also `-march=native` or `-msse4.2`. However, your PCL version is quite old, and I would recommend you to switch to a newer one. I believe there was a fix since then that solved this problem (on Linux, when using CMake).

Thank you for your suggestion, but the problem is still not solved. I also used pcl1.13 and the problem still occurred.

**Comment by mvieth** [comment]
I saw that you use a few other libraries in your project. I am not sure whether there might be some unfortunate interaction between PCL, Eigen, and one of those libraries.
Another thing you can try is add `-DEIGEN_HAS_CXX17_OVERALIGN=0` to your compiler options.

**Comment by timetosaygoodb** [comment]
> I saw that you use a few other libraries in your project. I am not sure whether there might be some unfortunate interaction between PCL, Eigen, and one of those libraries. Another thing you can try is add `-DEIGEN_HAS_CXX17_OVERALIGN=0` to your compiler options.
Thank you for your suggestion again, but it is still occurred. It makes me very distressed, in Chinese, 头皮发麻

**Comment by themightyoarfish** [comment]
be sure to add `${PCL_DEFINITIONS}` to your binary's compile definitions.

**Comment by mvieth** [comment]
@Hetols Can you provide a full backtrace, for example from valgrind or gdb? Do you build the laser_geometry package from source after you have installed your PCL build?

**Comment by mvieth** [comment]
@Hetols the backtrace suggests that the problem happens while freeing `co_sine_map_` in `LaserProjection` ( https://github.com/ros-perception/laser_geometry/blob/humble/include/laser_geometry/laser_geometry.hpp#L198 ). laser_geometry seems to be compiled as C++14, so try compiling your own project as C++14 as well (instead of C++17). Alternatively, try compiling your project with `-DEIGEN_HAS_CXX17_OVERALIGN=0`. Did you compile PCL as C++14? (this is the default)
Oh, and I assume you used the humble branch of laser_geometry when building it from source?

**Comment by yumingdong** [comment]
> I have also encountered a similar problem. Ubuntu 22.04 with ROS2 Humble.
> 
> @mvieth Previously, flag `-DEIGEN_HAS_CXX17_OVERALIGN=0` was automatically added by `add_definitions(${PCL_DEFINITIONS})`, and I only set my own project to use C++17, while PCL, laser_geometry (using the ros2 branch, not humble), and some other dependencies used the default C++ standard. However, based on your advice, I tried to rebuild PCL, laser_geometry (using the humble branch), and my own project with C++14, but I still got the same error.
> # CmakeLists
> 
> ```
> cmake_minimum_required(VERSION 3.24)
> project(virtual_lds)
> 
> # Set C++ standard
> set(CMAKE_CXX_STANDARD 14)
> set(TARGET_NAME ${PROJECT_NAME})
> 
> # Set compiler flags
> if (CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
>     add_compile_options(-Wall -Wextra -Wpedantic)
> endif ()
> 
> # Find dependencies
> find_package(ament_cmake REQUIRED)
> find_package(rclcpp REQUIRED)
> find_package(PCL 1.13 REQUIRED)
> find_package(pcl_conversions REQUIRED)
> find_package(std_msgs REQUIRED)
> find_package(sensor_msgs REQUIRED)
> find_package(laser_geometry HINTS "/usr/local/laser_geometry-humble-2.4.0")
> 
> # Set dependencies
> set(dependencies
>         PCL
>         rclcpp
>         std_msgs
>         sensor_msgs
>         laser_geometry
>         pcl_conversions
> )
> 
> # Include directories
> include_directories(
>         include
>         ${PCL_INCLUDE_DIRS}
>         ${rclcpp_INCLUDE_DIRS}
> )
> 
> # Build executable
> add_executable(main
>         src/main.cpp)
> 
> # Link libraries
> ament_target_dependencies(main ${dependencies})
> target_link_libraries(main ${PCL_LIBRARIES})
> 
> MESSAGE(STATUS "PCL_VERSION: ${PCL_VERSION}")
> MESSAGE(STATUS "PCL_LIBRARIES: ${PCL_LIBRARIES}")
> MESSAGE(STATUS "PCL_INCLUDE_DIRS: ${PCL_INCLUDE_DIRS}")
> MESSAGE(STATUS "PCL_DEFINITIONS: ${PCL_DEFINITIONS}")
> 
> # Add definitions
> add_definitions(${PCL_DEFINITIONS})
> 
> # Install executable
> install(TARGETS main
>         RUNTIME DESTINATION lib/${PROJECT_NAME})
> 
> # Install CMake config files
> ament_package()
> ```
> 
> # CmakeLog
> 
> ```
> -- Found ament_cmake: 1.3.6 (/opt/ros/humble/share/ament_cmake/cmake)
> -- Found rclcpp: 16.0.7 (/opt/ros/humble/share/rclcpp/cmake)
> -- Found rosidl_generator_c: 3.1.5 (/opt/ros/humble/share/rosidl_generator_c/cmake)
> -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
> -- Found rosidl_generator_cpp: 3.1.5 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
> -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
> -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
> -- Found rmw_implementation_cmake: 6.1.1 (/opt/ros/humble/share/rmw_implementation_cmake/cmake)
> -- Found rmw_fastrtps_cpp: 6.2.5 (/opt/ros/humble/share/rmw_fastrtps_cpp/cmake)
> -- Using RMW implementation 'rmw_fastrtps_cpp' as default
> CMake Warning (dev) at /usr/local/share/pcl-1.13/Modules/FindFLANN.cmake:45 (find_package):
>   Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
>   variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   CMake variable FLANN_ROOT is set to:
> 
>     /usr
> 
>   For compatibility, find_package is ignoring the variable, but code in a
>   .cmake module might still use it.
> Call Stack (most recent call first):
>   /usr/local/share/pcl-1.13/PCLConfig.cmake:258 (find_package)
>   /usr/local/share/pcl-1.13/PCLConfig.cmake:303 (find_flann)
>   /usr/local/share/pcl-1.13/PCLConfig.cmake:567 (find_external_library)
>   CMakeLists.txt:22 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- FLANN found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libflann_cpp.so)
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL GLX 
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
> -- OpenNI found (version: 1.5.4.0, include: /usr/include/ni, lib: /usr/lib/libOpenNI.so;libusb::libusb)
> -- OpenNI2 found (version: 2.2.0.33, include: /usr/include/openni2, lib: /usr/lib/x86_64-linux-gnu/libOpenNI2.so;libusb::libusb)
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL GLX 
> -- OpenNI found (version: 1.5.4.0, include: /usr/include/ni, lib: /usr/lib/libOpenNI.so;libusb::libusb)
> -- OpenNI2 found (version: 2.2.0.33, include: /usr/include/openni2, lib: /usr/lib/x86_64-linux-gnu/libOpenNI2.so;libusb::libusb)
> -- Found Qhull version 8.0.2
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
> -- looking for PCL_COMMON
> -- looking for PCL_KDTREE
> -- looking for PCL_OCTREE
> -- looking for PCL_SEARCH
> -- looking for PCL_SAMPLE_CONSENSUS
> -- looking for PCL_FILTERS
> -- looking for PCL_2D
> -- looking for PCL_GEOMETRY
> -- looking for PCL_IO
> -- looking for PCL_FEATURES
> -- looking for PCL_ML
> -- looking for PCL_SEGMENTATION
> -- looking for PCL_VISUALIZATION
> -- looking for PCL_SURFACE
> -- looking for PCL_REGISTRATION
> -- looking for PCL_KEYPOINTS
> -- looking for PCL_TRACKING
> -- looking for PCL_RECOGNITION
> -- looking for PCL_STEREO
> -- looking for PCL_OUTOFCORE
> -- looking for PCL_PEOPLE
> -- looking for PCL_SIMULATION
> -- Found PCL: pcl_common;pcl_kdtree;pcl_octree;pcl_search;pcl_sample_consensus;pcl_filters;pcl_io;pcl_features;pcl_ml;pcl_segmentation;pcl_visualization;pcl_surface;pcl_registration;pcl_keypoints;pcl_tracking;pcl_recognition;pcl_stereo;pcl_outofcore;pcl_people;pcl_simulation;Boost::system;Boost::filesystem;Boost::iostreams;Boost::serialization;/usr/lib/libOpenNI.so;libusb::libusb;/usr/lib/x86_64-linux-gnu/libOpenNI2.so;libusb::libusb;VTK::ChartsCore;VTK::CommonColor;VTK::CommonComputationalGeometry;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMath;VTK::CommonMisc;VTK::CommonTransforms;VTK::FiltersCore;VTK::FiltersExtraction;VTK::FiltersGeneral;VTK::FiltersGeometry;VTK::FiltersModeling;VTK::FiltersSources;VTK::ImagingCore;VTK::ImagingSources;VTK::InteractionImage;VTK::InteractionStyle;VTK::InteractionWidgets;VTK::IOCore;VTK::IOGeometry;VTK::IOImage;VTK::IOLegacy;VTK::IOPLY;VTK::RenderingAnnotation;VTK::RenderingCore;VTK::RenderingContext2D;VTK::RenderingLOD;VTK::RenderingFreeType;VTK::ViewsCore;VTK::ViewsContext2D;VTK::RenderingOpenGL2;VTK::RenderingContextOpenGL2;VTK::GUISupportQt;FLANN::FLANN;QHULL::QHULL (Required is at least version "1.13") 
> -- Found pcl_conversions: 2.4.0 (/opt/ros/humble/share/pcl_conversions/cmake)
> -- Found laser_geometry: 2.4.0 (/usr/local/laser_geometry-humble-2.4.0/share/laser_geometry/cmake)
> -- PCL_VERSION: 1.13.1.99
> -- PCL_LIBRARIES: pcl_common;pcl_kdtree;pcl_octree;pcl_search;pcl_sample_consensus;pcl_filters;pcl_io;pcl_features;pcl_ml;pcl_segmentation;pcl_visualization;pcl_surface;pcl_registration;pcl_keypoints;pcl_tracking;pcl_recognition;pcl_stereo;pcl_outofcore;pcl_people;pcl_simulation;Boost::system;Boost::filesystem;Boost::iostreams;Boost::serialization;/usr/lib/libOpenNI.so;libusb::libusb;/usr/lib/x86_64-linux-gnu/libOpenNI2.so;libusb::libusb;VTK::ChartsCore;VTK::CommonColor;VTK::CommonComputationalGeometry;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMath;VTK::CommonMisc;VTK::CommonTransforms;VTK::FiltersCore;VTK::FiltersExtraction;VTK::FiltersGeneral;VTK::FiltersGeometry;VTK::FiltersModeling;VTK::FiltersSources;VTK::ImagingCore;VTK::ImagingSources;VTK::InteractionImage;VTK::InteractionStyle;VTK::InteractionWidgets;VTK::IOCore;VTK::IOGeometry;VTK::IOImage;VTK::IOLegacy;VTK::IOPLY;VTK::RenderingAnnotation;VTK::RenderingCore;VTK::RenderingContext2D;VTK::RenderingLOD;VTK::RenderingFreeType;VTK::ViewsCore;VTK::ViewsContext2D;VTK::RenderingOpenGL2;VTK::RenderingContextOpenGL2;VTK::GUISupportQt;FLANN::FLANN;QHULL::QHULL
> -- PCL_INCLUDE_DIRS: /usr/local/include/pcl-1.13;/usr/local/include/eigen3;/usr/include;/usr/include/ni;/usr/include/openni2
> -- PCL_DEFINITIONS: -DEIGEN_HAS_CXX17_OVERALIGN=0
> -- Configuring done (2.7s)
> -- Generating done (0.0s)
> ```
> 
> # Code & Error & GDB Info
> 
> Same as before

Have you solved this problem? I have encounter same problem, my develop environment is: **Ubuntu 22.04 with ROS2 Humble pcl 1.12.1(install through apt install)**
And when I use asan address tools , get following errors:
`station_detection_node-1] [INFO] [1708398217.234414429] [rclcpp]: signal_handler(signum=2)
[station_detection_node-1] =================================================================
[station_detection_node-1] ==191140==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d00004e278 at pc 0x7f1a1afd1662 bp 0x7ffd1626ceb0 sp 0x7ffd1626cea0
[station_detection_node-1] READ of size 8 at 0x61d00004e278 thread T0
[station_detection_node-1]     #0 0x7f1a1afd1661 in Eigen::internal::handmade_aligned_free(void*) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:118
[station_detection_node-1]     #1 0x7f1a1afd1661 in Eigen::internal::aligned_free(void*) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:206
[station_detection_node-1]     #2 0x7f1a1afd1661 in Eigen::aligned_allocator<pcl::PointXYZI>::deallocate(pcl::PointXYZI*, unsigned long) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:921
[station_detection_node-1]     #3 0x7f1a1afd1661 in std::allocator_traits<Eigen::aligned_allocator<pcl::PointXYZI> >::deallocate(Eigen::aligned_allocator<pcl::PointXYZI>&, pcl::PointXYZI*, unsigned long) /usr/include/c++/11/bits/alloc_traits.h:345
[station_detection_node-1]     #4 0x7f1a1afd1661 in std::_Vector_base<pcl::PointXYZI, Eigen::aligned_allocator<pcl::PointXYZI> >::_M_deallocate(pcl::PointXYZI*, unsigned long) /usr/include/c++/11/bits/stl_vector.h:354
[station_detection_node-1]     #5 0x7f1a1afd1661 in std::_Vector_base<pcl::PointXYZI, Eigen::aligned_allocator<pcl::PointXYZI> >::~_Vector_base() /usr/include/c++/11/bits/stl_vector.h:335
[station_detection_node-1]     #6 0x7f1a1afd1661 in std::vector<pcl::PointXYZI, Eigen::aligned_allocator<pcl::PointXYZI> >::~vector() /usr/include/c++/11/bits/stl_vector.h:683
[station_detection_node-1]     #7 0x7f1a1afd1661 in pcl::PointCloud<pcl::PointXYZI>::~PointCloud() /usr/include/pcl-1.12/pcl/point_cloud.h:172
[station_detection_node-1]     #8 0x7f1a1afd1661 in std::_Sp_counted_ptr<pcl::PointCloud<pcl::PointXYZI>*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/11/bits/shared_ptr_base.h:348
[station_detection_node-1]     #9 0x7f1a1affc2a6 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/11/bits/shared_ptr_base.h:168
[station_detection_node-1]     #10 0x7f1a1b033cad in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/11/bits/shared_ptr_base.h:705
[station_detection_node-1]     #11 0x7f1a1b033cad in std::__shared_ptr<pcl::PointCloud<pcl::PointXYZI> const, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/11/bits/shared_ptr_base.h:1154
[station_detection_node-1]     #12 0x7f1a1b033cad in std::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const>::~shared_ptr() /usr/include/c++/11/bits/shared_ptr.h:122
[station_detection_node-1]     #13 0x7f1a1b033cad in pcl::Registration<pcl::PointXYZI, pcl::PointXYZI, float>::~Registration() /usr/include/pcl-1.12/pcl/registration/registration.h:137
[station_detection_node-1]     #14 0x7f1a1b1efd75 in pcl::IterativeClosestPoint<pcl::PointXYZI, pcl::PointXYZI, float>::~IterativeClosestPoint() /usr/include/pcl-1.12/pcl/registration/icp.h:184
[station_detection_node-1]     #15 0x7f1a1b1efd75 in station_detect_pkg::StationDetection::~StationDetection() /home/ymdong4/slam_code/iflytek_slam/localization_and_mapping/src/cartographer_ros/cartographer_ros/cartographer_ros/include/station_detection.h:45
[station_detection_node-1]     #16 0x558adaea79c6 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/11/bits/shared_ptr_base.h:168
[station_detection_node-1]     #17 0x558adae7a328 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/11/bits/shared_ptr_base.h:705
[station_detection_node-1]     #18 0x558adae7a328 in std::__shared_ptr<station_detect_pkg::StationDetection, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/11/bits/shared_ptr_base.h:1154
[station_detection_node-1]     #19 0x558adae7a328 in std::shared_ptr<station_detect_pkg::StationDetection>::~shared_ptr() /usr/include/c++/11/bits/shared_ptr.h:122
[station_detection_node-1]     #20 0x558adae7a328 in main /home/ymdong4/slam_code/iflytek_slam/localization_and_mapping/src/cartographer_ros/cartographer_ros/cartographer_ros/src/station_detection_node.cpp:68
[station_detection_node-1]     #21 0x7f1a0a3f5d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
[station_detection_node-1]     #22 0x7f1a0a3f5e3f in __libc_start_main_impl ../csu/libc-start.c:392
[station_detection_node-1]     #23 0x558adae7a834 in _start (/home/ymdong4/slam_code/iflytek_slam/localization_and_mapping/install/lib/cartographer_ros/station_detection_node+0x69834)
[station_detection_node-1] 
[station_detection_node-1] 0x61d00004e278 is located 8 bytes to the left of 2048-byte region [0x61d00004e280,0x61d00004ea80)
[station_detection_node-1] allocated by thread T0 here:
[station_detection_node-1]     #0 0x7f1a1bd89887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
[station_detection_node-1]     #1 0x7f1a1127ea40  (/lib/x86_64-linux-gnu/libpcl_filters.so.1.12+0x55aa40)
[station_detection_node-1] 
[station_detection_node-1] SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/eigen3/Eigen/src/Core/util/Memory.h:118 in Eigen::internal::handmade_aligned_free(void*)
[station_detection_node-1] Shadow bytes around the buggy address:
[station_detection_node-1]   0x0c3a80001bf0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
[station_detection_node-1]   0x0c3a80001c00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
[station_detection_node-1]   0x0c3a80001c10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
[station_detection_node-1]   0x0c3a80001c20: fd fd fd fd fd fa fa fa fa fa fa fa fa fa fa fa
[station_detection_node-1]   0x0c3a80001c30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
[station_detection_node-1] =>0x0c3a80001c40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
[station_detection_node-1]   0x0c3a80001c50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[station_detection_node-1]   0x0c3a80001c60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[station_detection_node-1]   0x0c3a80001c70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[station_detection_node-1]   0x0c3a80001c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[station_detection_node-1]   0x0c3a80001c90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[station_detection_node-1] Shadow byte legend (one shadow byte represents 8 application bytes):
[station_detection_node-1]   Addressable:           00
[station_detection_node-1]   Partially addressable: 01 02 03 04 05 06 07 
[station_detection_node-1]   Heap left redzone:       fa
[station_detection_node-1]   Freed heap region:       fd
[station_detection_node-1]   Stack left redzone:      f1
[station_detection_node-1]   Stack mid redzone:       f2
[station_detection_node-1]   Stack right redzone:     f3
[station_detection_node-1]   Stack after return:      f5
[station_detection_node-1]   Stack use after scope:   f8
[station_detection_node-1]   Global redzone:          f9
[station_detection_node-1]   Global init order:       f6
[station_detection_node-1]   Poisoned by user:        f7
[station_detection_node-1]   Container overflow:      fc
[station_detection_node-1]   Array cookie:            ac
[station_detection_node-1]   Intra object redzone:    bb
[station_detection_node-1]   ASan internal:           fe
[station_detection_node-1]   Left alloca redzone:     ca
[station_detection_node-1]   Right alloca redzone:    cb
[station_detection_node-1]   Shadow gap:              cc
[station_detection_node-1] ==191140==ABORTING
`

**Comment by mvieth** [comment]
@yumingdong Make sure that your code is compiled with AVX, AVX2, and AVX512 disabled, or try using `#define PCL_NO_PRECOMPILE`

**Comment by yumingdong** [comment]
> @yumingdong Make sure that your code is compiled with AVX, AVX2, and AVX512 disabled, or try using `#define PCL_NO_PRECOMPILE`

I have use `#define PCL_NO_PRECOMPILE` macro in x86 PC can solve this problem, but in arm platform compile code supplys: 
`/../lib/gcc/aarch64-buildroot-linux-gnu/10.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: CMakeFiles/station_detection_node.dir/src/station_detection.cpp.o: undefined reference to symbol 'LZ4_compress_HC_continue'
../lib/gcc/aarch64-buildroot-linux-gnu/10.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /home/jsxu4/rk3588_buildroot_toolchain/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib64/libflann_cpp.so.1.9: error adding symbols: DSO missing from command line`
Can you solve this problem?

**Comment by TOMO-CAT** [comment]
> @yumingdong Make sure that your code is compiled with AVX, AVX2, and AVX512 disabled, or try using `#define PCL_NO_PRECOMPILE`

add `-DPCL_NO_PRECOMPILE=ON` flags in x86 can also solve the double-free problem for me，could you please explain how it work? thans very much

here is my gdb backtrace：

![image](https://github.com/PointCloudLibrary/pcl/assets/47598093/443549d0-b861-427c-8b9c-50cd5faaa1b9)

Since I can't abstract the code into a minimum example yet, I would not show the code now.

**Comment by francismelon** [comment]
I have the same problem, but my situation is different from yours. My program and a dependent library use pcl, and the program compilation is enabled `-msse4.2-mfpmath = sse-march = native-mavx2`, but it is not when the library is compiled. When they involve pcl content interaction, the same problem occurs during the process of destruction. I think it is necessary to check whether there is such a difference in compilation options in my project.
